apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-dpl
spec:
  template:
    spec:
      containers:
      - name: inventario
        env:
        - name: NATS_SVR
          value: "nats://dev-nats-svr:4222"
