apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
commonLabels:
  env: stg
namePrefix: stg-
bases:
  - ../base
secretGenerator:
  - name: dbpassword
    literals:
      - "password=mega$bite2024stg"
resources:
  - namespace.yaml
patchesStrategicMerge:
  - nats-patch.yaml
  - compras-patch.yaml
  - comprasback-patch.yaml
  - inventario-patch.yaml
  - ingress-patch.yaml