apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
namePrefix: stg-
secretGenerator:
- literals:
  - password=mega$bite2024stg
  name: dbpassword
resources:
- namespace.yaml
- ../base
labels:
- includeSelectors: true
  pairs:
    env: stg
patches:
- path: nats-patch.yaml
- path: compras-patch.yaml
- path: comprasback-patch.yaml
- path: inventario-patch.yaml
- path: ingress-patch.yaml
