apiVersion: apps/v1
kind: Pod
metadata:
  name: postgres-db
spec:
  template:
    spec:
      containers:
        - name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: ""
              valueFrom:
                secretKeyRef:
                  name: dbpassword
                  key: password
