apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonLabels:
  env: prd
namePrefix: prd-
bases:
  - ../base
secretGenerator:
  - name: dbpassword
    literals:
      - "password=mega$bite2024dev"
resources:
  - namespace.yaml
patchesStrategicMerge:
  - nats-patch.yaml
  - compras-patch.yaml
  - comprasback-patch.yaml
  - inventario-patch.yaml
  - ingress-patch.yaml